export type movieType = {
  id: string,
  name: string,
  imageUrl: string,
  description: string,
  typeId: string,
  productionYear: number,
  imdbScore: string,
  director: string,
  actor: string,
  tag: string,
  videoLink: string,
  thumbnailLink: string,
  createDate: Date,
  updatedDate: Date,
  isActive: boolean,
  createdUser: number,
  updatedUser: number,
  watchCount: number
};
